// <auto-generated />
namespace Practica4_GrafovaKL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SetFieldsUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetFieldsUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202206250648341_Set-FieldsUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
